//
// Created by tjooris on 1/5/26.
//

#ifndef CPP_MODULE_05_ROBOTOMYREQUESTFORM_HPP
#define CPP_MODULE_05_ROBOTOMYREQUESTFORM_HPP


class RobotomyRequestForm
{
};


#endif //CPP_MODULE_05_ROBOTOMYREQUESTFORM_HPP