//
// Created by tjooris on 1/5/26.
//

#ifndef CPP_MODULE_05_SHRUBBERYCREATIONFORM_HPP
#define CPP_MODULE_05_SHRUBBERYCREATIONFORM_HPP


class ShrubberyCreationForm
{
};


#endif //CPP_MODULE_05_SHRUBBERYCREATIONFORM_HPP